name: Build DFPS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c # Or specify the version required by your project

    - name: Grant execute permission for build script
      run: chmod +x build.sh

    - name: Build and package DFPS
      run: ./build.sh Release "make"
      env:
        ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }} # Ensure the script uses the NDK path set by the action

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dfps
        path: build/package/dfps
